### ISSUE TITLE
Regarding the xml input file

### ISSUE THREAD

**Issue by lepmik** [dekamps/miind#23]
**Attributes vs single valued elements in input.xml**
As of now the input xml have many single valued elements e.g.
```xml
<CanvasParameter>
      <T_min>0</T_min>
      <T_max>1.</T_max>
      <F_min>0</F_min>
</CanvasParameter>
```
I propose to have these elements as attributes in stead, i.e.
```xml
<CanvasParameter
    T_max="1."
    T_min="0"
    F_min="0"
/>
```
Thus conforming to `json`, `yaml`, i.e.
```json
{
"CanvasParameter": {
   "T_max": "1.",
   "T_min": "0",
   "F_min": "0",
   }
}
```
```yaml
'CanvasParameter': 
    - 'T_max': '1.'
    - 'T_min': '0'
    - 'F_min': '0'
```
In addition to conforming to multiple formats one also ease the building of python interfaces through working with dictionaries.
